import { useState } from "react";
import { useQuery } from "@tanstack/react-query";

type StateStats = { sample_count: number; sample_quality: string; median_return_10: number | null; positive_rate_10: number | null; median_mfe_10: number | null; median_mae_10: number | null; median_return_5: number | null; median_return_20: number | null };
type Summary = { states: Record<string, StateStats> };
const request = async (path: string) => { const result = await fetch(path); if (!result.ok) throw new Error(await result.text()); return result.json(); };

/** Decision Validation tab content; forward outcomes are research observations, not trades. */
export function DecisionValidationLab() {
  const [symbol, setSymbol] = useState("VXN"), [timeframe, setTimeframe] = useState("1d"), [sampling, setSampling] = useState("TRANSITION");
  const query = useQuery<Summary>({ queryKey: ["decision-validation", symbol, timeframe, sampling], queryFn: () => request(`/api/backtest/decisions/${symbol}?timeframe=${timeframe}&sampling_mode=${sampling}`), retry: false }); const pct = (v: number | null | undefined) => v == null ? "—" : `${(v * 100).toFixed(1)}%`;
  return <section className="panel p-4"><div className="toolbar"><div><div className="panel-title">Decision Validation</div><p className="muted">Forward-return observations after point-in-time research states.</p></div><div className="flex gap-2"><input className="terminal-input w-24" value={symbol} onChange={e => setSymbol(e.target.value.toUpperCase())}/><select className="terminal-input" value={timeframe} onChange={e => setTimeframe(e.target.value)}><option value="1d">1D</option><option value="1w">1W</option><option value="1mo">1MO</option></select><select className="terminal-input" value={sampling} onChange={e => setSampling(e.target.value)}><option value="TRANSITION">TRANSITION</option><option value="DAILY">DAILY</option></select></div></div><div className="grid grid-cols-4 gap-3">{["BUY", "WATCH", "WAIT", "RISK"].map(state => { const s = query.data?.states[state]; return <div className="border border-zinc-800 p-3 text-sm" key={state}><b>{state}</b><span>Samples · {s?.sample_count ?? "—"} · {s?.sample_quality ?? "—"}</span><span>10D Median · {pct(s?.median_return_10)}</span><span>10D Positive Rate · {pct(s?.positive_rate_10)}</span><span>10D MFE / MAE · {pct(s?.median_mfe_10)} / {pct(s?.median_mae_10)}</span></div>; })}</div><section className="target-table"><div className="panel-title">Decision Comparison</div><table><thead><tr><th>State</th><th>Samples</th><th>5D Median</th><th>10D Median</th><th>20D Median</th><th>10D MFE</th><th>10D MAE</th><th>Positive Rate</th></tr></thead><tbody>{["BUY", "WATCH", "WAIT", "RISK"].map(state => { const s = query.data?.states[state]; return <tr key={state}><td>{state}</td><td>{s?.sample_count ?? "—"}</td><td>{pct(s?.median_return_5)}</td><td>{pct(s?.median_return_10)}</td><td>{pct(s?.median_return_20)}</td><td>{pct(s?.median_mfe_10)}</td><td>{pct(s?.median_mae_10)}</td><td>{pct(s?.positive_rate_10)}</td></tr>; })}</tbody></table></section></section>;
}
