import { useQuery } from "@tanstack/react-query";

type Citation = { id: string; source: string; title: string; published_at: string; url: string | null; analysis: { direction: string; event_type: string } };
type Decision = { state: "BUY" | "WATCH" | "WAIT" | "RISK"; confidence: number; scores: { bullish: number; bearish: number }; confirmations: { count: number; delta: boolean; trend: boolean; signal: boolean; volume: boolean; historical: boolean; news: boolean }; missing_conditions: string[]; risk_factors: Array<{ code: string; severity: string; message: string }>; news_trace?: { status: string; company?: { direction: string; score: number; confidence: number }; high_risk?: Citation[]; citations?: Citation[]; reason?: string } };
const fetchDecision = async (path: string) => { const result = await fetch(path); if (!result.ok) throw new Error(await result.text()); return result.json(); };

/** Compact research-state card.  It intentionally has no broker or order controls. */
export function DecisionStateCard({ symbol, timeframe }: { symbol: string; timeframe: string }) {
  const query = useQuery<Decision>({ queryKey: ["decision", symbol, timeframe], queryFn: () => fetchDecision(`/api/decision/${symbol}?timeframe=${timeframe}`), retry: false }); const d = query.data;
  const pct = (value?: number) => value == null ? "—" : `${Math.round(value * 100)}%`;
  const news = d?.news_trace;
  return <section className="panel p-4"><div className="panel-title">研究状态 <span className="float-right text-xs font-normal text-zinc-500">Research only</span></div><div className="grid grid-cols-5 gap-3 text-sm"><div><span>Decision State</span><b>{d?.state ?? "—"}</b></div><div><span>Research Confidence</span><b>{pct(d?.confidence)}</b></div><div><span>Bullish Evidence</span><b>{pct(d?.scores.bullish)}</b></div><div><span>Bearish Evidence</span><b>{pct(d?.scores.bearish)}</b></div><div><span>Confirmations</span><b>{d ? `${d.confirmations.count} / 5` : "—"}</b></div></div><div className="mt-4 grid grid-cols-2 gap-4 border-t border-zinc-800 pt-3 text-xs"><div><span className="text-zinc-500">Current confirmations</span>{d && Object.entries(d.confirmations).filter(([key, value]) => key !== "count" && value).map(([key]) => <p key={key}>✓ {key}</p>)}</div><div><span className="text-zinc-500">Still awaiting</span>{d?.missing_conditions.map(reason => <p key={reason}>○ {reason}</p>)}</div></div>{news && <div className="news-evidence"><b>新闻依据</b>{news.status === "AVAILABLE" && news.company ? <><p>公司情绪：{news.company.direction} · {pct(Math.abs(news.company.score))} · 可信度 {pct(news.company.confidence)}</p>{(news.high_risk?.length ? news.high_risk : news.citations ?? []).map(item => <p key={item.id}>• {item.source}｜{item.title}{item.url && <a href={item.url} target="_blank" rel="noreferrer"> 原文</a>}</p>)}</> : <p>{news.reason ?? "暂无可用于决策的白名单新闻来源。"}</p>}</div>}{d?.state === "RISK" && <div className="mt-3 border-t border-zinc-800 pt-3 text-xs text-amber-300">{d.risk_factors.map(factor => <p key={factor.code}>{factor.severity}: {factor.message}</p>)}</div>}</section>;
}
