import { useMemo, useState } from "react";
import { Activity, CandlestickChart, CircleAlert, Gauge, ListFilter, Volume2 } from "lucide-react";
import { Area, Bar, CartesianGrid, ComposedChart, Line, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";

export type GpmaRow = {
  time: string; close: number; atr_26: number; ma_120: number; ma_250: number; diff: number; dea: number; macd: number;
  volume: number; vol_ma_20: number; volume_ratio: number | null; gap_rate: number | null;
  ema_8: number; ema_10: number; ema_12: number; ema_15: number; ema_20: number; ema_40: number; ema_45: number; ema_50: number; ema_55: number; ema_60: number;
  bull_bg: boolean; bull_strong: boolean; bear_bg: boolean; vol_ok: boolean; vol_strong: boolean; gap_ok: boolean; range_ok: boolean; top_confirm: boolean; bottom_confirm: boolean; buy_ok: boolean; buy_strong_ok: boolean; sell_ok: boolean;
  b1_raw: boolean; b2_raw: boolean; b3_raw: boolean; s1_raw: boolean; s2_raw: boolean; b1: boolean; b2: boolean; b3: boolean; s1: boolean; s2: boolean;
  top_1_raw: boolean; top_2_raw: boolean; top_3_raw: boolean; bottom_1_raw: boolean; bottom_2_raw: boolean; bottom_3_raw: boolean;
};

const signalNames: Array<[keyof GpmaRow, string, "up" | "down"]> = [["b1", "B1", "up"], ["b2", "B2", "up"], ["b3", "B3", "up"], ["s1", "S1", "down"], ["s2", "S2", "down"]];
const flag = (on: boolean, label: string, positive = true) => <span className={on ? positive ? "gpma-flag on" : "gpma-flag risk" : "gpma-flag"}>{on ? "✓" : "—"} {label}</span>;
const number = (value: number | null | undefined, digits = 2) => value == null || !Number.isFinite(value) ? "—" : value.toFixed(digits);

export function GpmaProWorkbench({ rows, symbol, timeframe, asOf }: { rows: GpmaRow[]; symbol: string; timeframe: string; asOf?: string }) {
  const [windowSize, setWindowSize] = useState(120);
  const [tab, setTab] = useState<"momentum" | "volume">("momentum");
  const data = useMemo(() => rows.slice(-windowSize), [rows, windowSize]);
  const latest = rows.at(-1);
  if (!latest) return <section className="panel p-5"><p className="muted">等待 GPMAPRO 序列数据。请先导入包含 OHLCV 的本地 CSV。</p></section>;
  const trend = latest.bull_strong ? "强势多头" : latest.bull_bg ? "多头结构" : latest.bear_bg ? "空头结构" : "中性整理";
  const signals = signalNames.filter(([key]) => latest[key]).map(([, label]) => label);
  const divergence = [["顶部", latest.top_1_raw || latest.top_2_raw || latest.top_3_raw], ["底部", latest.bottom_1_raw || latest.bottom_2_raw || latest.bottom_3_raw]] as const;
  return <div className="terminal-page gpma-page">
    <div className="page-heading"><div><h1>GPMAPRO 指标工作台</h1><p>公式状态、动量、成交量、过滤器与原始背离条件；所有字段均来自同一时点的无未来函数计算。</p></div><div className="gpma-asof">{symbol} · {timeframe} · as of {asOf ?? latest.time}</div></div>
    <section className="gpma-strip"><div><span>市场结构</span><b className={latest.bear_bg ? "text-rose-300" : "text-emerald-300"}>{trend}</b><small>收盘 {number(latest.close)}</small></div><div><span>MACD 动量</span><b className={latest.macd >= 0 ? "text-emerald-300" : "text-rose-300"}>{number(latest.macd, 4)}</b><small>DIFF {number(latest.diff, 4)} · DEA {number(latest.dea, 4)}</small></div><div><span>相对成交量</span><b>{number(latest.volume_ratio)}×</b><small>{number(latest.volume).toLocaleString()} / MA20 {number(latest.vol_ma_20).toLocaleString()}</small></div><div><span>ATR(26)</span><b>{number(latest.atr_26)}</b><small>Gap {number((latest.gap_rate ?? 0) * 100)}%</small></div><div><span>最终信号</span><b>{signals.join(" · ") || "无"}</b><small>{divergence.filter(([, on]) => on).map(([name]) => `${name}背离预警`).join(" · ") || "无背离预警"}</small></div></section>
    <div className="gpma-toolbar"><div className="inline-flex items-center gap-2 text-sm text-zinc-400"><CandlestickChart size={16} /> 显示区间</div><div className="flex border border-zinc-700">{[60, 120, 250].map((value) => <button key={value} onClick={() => setWindowSize(value)} className={windowSize === value ? "gpma-tab active" : "gpma-tab"}>{value} bars</button>)}</div></div>
    <div className="grid grid-cols-[1fr_320px] gap-4"><section className="panel p-4"><div className="panel-title flex items-center gap-2"><Activity size={16} className="text-cyan-300" />趋势与均线结构</div><div className="h-[300px]"><ResponsiveContainer><ComposedChart data={data}><CartesianGrid stroke="#27272a" vertical={false}/><XAxis dataKey="time" minTickGap={48} tick={{fill:"#71717a",fontSize:11}}/><YAxis domain={["auto","auto"]} tick={{fill:"#71717a",fontSize:11}} width={48}/><Tooltip contentStyle={{background:"#09090b",border:"1px solid #3f3f46"}}/><Line dataKey="close" stroke="#e4e4e7" dot={false} strokeWidth={1.5}/><Line dataKey="ema_8" stroke="#fb7185" dot={false}/><Line dataKey="ema_20" stroke="#f59e0b" dot={false}/><Line dataKey="ema_60" stroke="#34d399" dot={false}/><Line dataKey="ma_120" stroke="#22d3ee" dot={false} strokeDasharray="4 3"/><Line dataKey="ma_250" stroke="#a78bfa" dot={false} strokeDasharray="4 3"/></ComposedChart></ResponsiveContainer></div><div className="gpma-legend"><span className="close">Close</span><span className="ema8">EMA 8</span><span className="ema20">EMA 20</span><span className="ema60">EMA 60</span><span className="ma120">MA 120</span><span className="ma250">MA 250</span></div></section>
      <section className="panel p-4"><div className="panel-title flex items-center gap-2"><ListFilter size={16} className="text-cyan-300" />公式过滤状态</div><div className="gpma-flags">{flag(latest.bull_bg, "多头背景")}{flag(latest.bull_strong, "强多头")}{flag(latest.bear_bg, "空头背景", false)}{flag(latest.vol_ok, "成交量达标")}{flag(latest.vol_strong, "成交量强")}{flag(latest.gap_ok, "跳空合格")}{flag(latest.range_ok, "波动范围合格")}{flag(latest.buy_ok, "买入环境")}{flag(latest.buy_strong_ok, "强买入环境")}{flag(latest.sell_ok, "卖出环境")}{flag(latest.top_confirm, "顶部确认", false)}{flag(latest.bottom_confirm, "底部确认")}</div><div className="mt-5 border-t border-zinc-800 pt-3 text-xs text-zinc-500">最终 B/S 信号会在原始公式条件成立后，继续经过环境过滤和近期重复抑制；背离为预警，不等于 B/S 信号。</div></section></div>
    <section className="panel mt-4 p-4"><div className="flex items-center justify-between"><div className="panel-title mb-0 flex items-center gap-2">{tab === "momentum" ? <Gauge size={16} className="text-cyan-300"/> : <Volume2 size={16} className="text-cyan-300"/>}{tab === "momentum" ? "MACD / DEA 动量窗" : "成交量确认窗"}</div><div className="flex border border-zinc-700"><button onClick={() => setTab("momentum")} className={tab === "momentum" ? "gpma-tab active" : "gpma-tab"}>动量</button><button onClick={() => setTab("volume")} className={tab === "volume" ? "gpma-tab active" : "gpma-tab"}>成交量</button></div></div><div className="mt-3 h-[250px]"><ResponsiveContainer>{tab === "momentum" ? <ComposedChart data={data}><CartesianGrid stroke="#27272a" vertical={false}/><XAxis dataKey="time" minTickGap={48} tick={{fill:"#71717a",fontSize:11}}/><YAxis tick={{fill:"#71717a",fontSize:11}} width={48}/><Tooltip contentStyle={{background:"#09090b",border:"1px solid #3f3f46"}}/><Bar dataKey="macd" fill="#22d3ee88"/><Line dataKey="diff" stroke="#f59e0b" dot={false}/><Line dataKey="dea" stroke="#f472b6" dot={false}/></ComposedChart> : <ComposedChart data={data}><CartesianGrid stroke="#27272a" vertical={false}/><XAxis dataKey="time" minTickGap={48} tick={{fill:"#71717a",fontSize:11}}/><YAxis tick={{fill:"#71717a",fontSize:11}} width={55}/><Tooltip contentStyle={{background:"#09090b",border:"1px solid #3f3f46"}}/><Bar dataKey="volume" fill="#22d3ee66"/><Line dataKey="vol_ma_20" stroke="#f59e0b" dot={false}/><Area dataKey="volume_ratio" stroke="#34d399" fill="#34d39922" yAxisId="ratio"/><YAxis yAxisId="ratio" orientation="right" tick={{fill:"#71717a",fontSize:11}} width={42}/></ComposedChart>}</ResponsiveContainer></div></section>
    <section className="panel mt-4 overflow-hidden"><div className="flex items-center gap-2 border-b border-zinc-800 px-4 py-3 text-sm font-semibold"><CircleAlert size={16} className="text-cyan-300"/>最近公式事件（最终信号与原始预警分列）</div><table><thead><tr><th>日期</th><th>最终 B/S</th><th>原始 B/S 条件</th><th>顶部背离</th><th>底部背离</th><th>环境</th></tr></thead><tbody>{[...data].reverse().filter(row => signalNames.some(([key]) => row[key]) || row.top_1_raw || row.top_2_raw || row.top_3_raw || row.bottom_1_raw || row.bottom_2_raw || row.bottom_3_raw).slice(0, 20).map(row => <tr key={row.time}><td>{row.time}</td><td className="text-zinc-100">{signalNames.filter(([key]) => row[key]).map(([, name]) => name).join(" · ") || "—"}</td><td>{[["B1",row.b1_raw],["B2",row.b2_raw],["B3",row.b3_raw],["S1",row.s1_raw],["S2",row.s2_raw]].filter(([,on])=>on).map(([name])=>name).join(" · ") || "—"}</td><td>{[["T1",row.top_1_raw],["T2",row.top_2_raw],["T3",row.top_3_raw]].filter(([,on])=>on).map(([name])=>name).join(" · ") || "—"}</td><td>{[["B1",row.bottom_1_raw],["B2",row.bottom_2_raw],["B3",row.bottom_3_raw]].filter(([,on])=>on).map(([name])=>name).join(" · ") || "—"}</td><td>{row.buy_ok ? "买入环境" : row.sell_ok ? "卖出环境" : "过滤未满足"}</td></tr>)} </tbody></table></section>
  </div>;
}
