import { useState } from "react";
import { useQuery } from "@tanstack/react-query";

const request = async (path: string) => { const response = await fetch(path); if (!response.ok) throw new Error(await response.text()); return response.json(); };
type Snapshot = { as_of: string; evidence_balance: string; confidence: number; scores: { bullish: number; bearish: number }; conflicts: unknown[]; evidence: Array<{ id: string; category: string; label: string; direction: string; strength: number; confidence: number; status: string; source: string; details: Record<string, unknown> }>; data_quality: { freshness: string } };

export function MarketEvidence() {
  const [symbol, setSymbol] = useState("VXN"), [timeframe, setTimeframe] = useState("1d"), [selected, setSelected] = useState<Snapshot["evidence"][number] | null>(null);
  const query = useQuery<Snapshot>({ queryKey: ["evidence", symbol, timeframe], queryFn: () => request(`/api/evidence/${symbol}?timeframe=${timeframe}`), retry: false }); const d = query.data; const pct = (x?: number) => x == null ? "—" : `${Math.round(x * 100)}%`;
  return <div className="terminal-page"><div className="page-heading"><div><h1>市场证据 <span className="text-sm font-normal text-zinc-500">Market Evidence</span></h1><p>统一展示时间、技术结构、成交量、历史与数据质量证据；不提供交易指令。</p></div><div className="flex gap-2"><input className="terminal-input w-24" value={symbol} onChange={e => setSymbol(e.target.value.toUpperCase())}/><select className="terminal-input" value={timeframe} onChange={e => setTimeframe(e.target.value)}><option value="1d">日线</option><option value="1w">周线</option><option value="1mo">月线</option></select></div></div><section className="panel p-4"><div className="grid grid-cols-5 gap-3 text-sm"><div><span>Evidence Balance</span><b>{d?.evidence_balance ?? "—"}</b></div><div><span>Bullish Evidence</span><b>{pct(d?.scores.bullish)}</b></div><div><span>Bearish Evidence</span><b>{pct(d?.scores.bearish)}</b></div><div><span>Confidence</span><b>{pct(d?.confidence)}</b></div><div><span>Conflicts</span><b>{d?.conflicts.length ?? "—"}</b></div></div></section><div className="mt-4 grid grid-cols-[1fr_360px] gap-4"><section className="panel overflow-hidden"><table><thead><tr><th>类别</th><th>证据</th><th>方向</th><th>强度</th><th>可信度</th><th>状态</th></tr></thead><tbody>{d?.evidence.map(x => <tr key={x.id} className="cursor-pointer hover:bg-zinc-900" onClick={() => setSelected(x)}><td>{x.category}</td><td>{x.label}</td><td>{x.direction}</td><td>{pct(x.strength)}</td><td>{pct(x.confidence)}</td><td>{x.status}</td></tr>)}</tbody></table></section><section className="panel p-4"><div className="panel-title">Evidence Detail</div>{selected ? <div className="metric-grid"><div><span>Source</span><b>{selected.source}</b></div><div><span>Direction</span><b>{selected.direction}</b></div><div><span>Strength</span><b>{pct(selected.strength)}</b></div><div><span>Confidence</span><b>{pct(selected.confidence)}</b></div><div><span>Details</span><b className="break-all text-xs">{JSON.stringify(selected.details)}</b></div></div> : <p className="muted">点击任一证据查看来源、方向、强度、可信度与明细。</p>}<div className="mt-5 border-t border-zinc-800 pt-3"><span className="text-xs text-zinc-500">Data Quality</span><b className="block text-sm">{d?.data_quality.freshness ?? "—"}</b></div></section></div></div>;
}
