import { useMemo, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { RefreshCw } from "lucide-react";
import { PageHeader, StatusBadge } from "@/components/ui/workspace";

type Signal = { kind: string; severity: "INFO" | "WATCH" | "RISK"; confidence: number; message: string; direction?: string };
type Alert = { id: string; symbol: string; created_at: string; scheduled_event: boolean; signals: Signal[]; relation: { kind: string; message: string }; aggregate: { call_volume: number; put_volume: number; atm_iv: number; top_strike: number | null } };
type Monitor = { health: { status: string; error?: string | null; last_snapshot_at?: string | null; limitations: string[] }; alerts: Alert[]; unread_count: number; last_check?: { captured_at: string; failures: Array<{ symbol: string; error: string }> } | null; coverage: { configured: number; max_per_scan: number } };
type Insight = { symbol: string; status: "AVAILABLE" | "NO_SNAPSHOT"; message?: string; latest?: { captured_at: string; scheduled_event: boolean; aggregate: { call_volume: number; put_volume: number; atm_iv: number; near_iv: number; far_iv: number; top_strike: number | null; top_contract: string | null }; signals: Signal[]; quality: { eligible_contracts: number } }; relation?: { kind: string; message: string }; limitations?: string[]; history?: Array<{ captured_at: string; atm_iv: number; option_volume: number; premium: number }>; contracts?: Array<{ contract: string; option_type: string; strike: number; expiry: string; dte: number; volume: number; open_interest: number; iv: number }> };

async function request<T>(path: string, init?: RequestInit): Promise<T> { const response = await fetch(path, init); if (!response.ok) throw new Error(await response.text()); return response.json(); }
const number = (value?: number | null, digits = 0) => value == null ? "—" : value.toLocaleString("zh-CN", { maximumFractionDigits: digits });
const formatTime = (value?: string | null) => value ? new Date(value).toLocaleString("zh-CN", { hour12: false }) : "—";
const tone = (severity?: string) => severity === "RISK" ? "negative" : severity === "WATCH" ? "warning" : "neutral";

export function OptionsRadar() {
  const [symbol, setSymbol] = useState("AAPL"); const [running, setRunning] = useState(false); const [error, setError] = useState<string | null>(null);
  const monitor = useQuery({ queryKey: ["option-monitor"], queryFn: () => request<Monitor>("/api/options/monitor"), retry: false });
  const insight = useQuery({ queryKey: ["option-insight", symbol], queryFn: () => request<Insight>(`/api/options/US.${encodeURIComponent(symbol)}/insight`), retry: false });
  const selected = useMemo(() => (insight.data?.status === "AVAILABLE" ? insight.data : null), [insight.data]);
  const prioritizedAlerts = useMemo(() => (monitor.data?.alerts ?? []).slice().sort((left, right) => {
    const score = (alert: Alert) => alert.signals.some(signal => signal.severity === "RISK") ? 2 : alert.signals.some(signal => signal.severity === "WATCH") ? 1 : 0;
    return score(right) - score(left) || right.created_at.localeCompare(left.created_at);
  }), [monitor.data?.alerts]);
  const scan = async (code?: string) => { setRunning(true); setError(null); try { await request(`/api/options/monitor/check${code ? `?code=US.${encodeURIComponent(code)}` : ""}`, { method: "POST" }); await Promise.all([monitor.refetch(), insight.refetch()]); } catch (reason) { setError(reason instanceof Error ? reason.message : String(reason)); } finally { setRunning(false); } };
  return <div className="terminal-page">
    <PageHeader title="期权雷达" description="独立扫描美股期权链、隐含波动率与异常活跃度；所有方向都只是研究假设，不构成交易指令。" actions={<div className="flex gap-2"><input className="terminal-input w-28" value={symbol} onChange={event => setSymbol(event.target.value.toUpperCase().replace(/^US\./, ""))} aria-label="期权标的"/><button className="secondary-button inline-flex items-center gap-1" onClick={() => void scan(symbol)} disabled={running}><RefreshCw size={14}/>{running ? "扫描中" : "扫描标的"}</button><button className="primary-button inline-flex items-center gap-1" onClick={() => void scan()} disabled={running}><RefreshCw size={14}/>扫描候选池</button></div>} />
    <section className={`panel panel-evidence options-health p-4 ${monitor.data?.health.status === "AVAILABLE" ? "is-ready" : "is-blocked"}`}><div className="grid grid-cols-4 gap-4 text-sm"><div><span>OpenD 状态</span><b className="block mt-1"><StatusBadge tone={monitor.data?.health.status === "AVAILABLE" ? "positive" : "warning"}>{monitor.data?.health.status || "检查中"}</StatusBadge></b></div><div><span>最新快照</span><b className="block mt-1">{formatTime(monitor.data?.health.last_snapshot_at)}</b></div><div><span>未读异常</span><b className="block mt-1">{monitor.data?.unread_count ?? "—"}</b></div><div><span>扫描范围</span><b className="block mt-1">{monitor.data?.coverage.max_per_scan ?? "—"} / {monitor.data?.coverage.configured ?? "—"} 标的</b></div></div>{monitor.data?.health.error && <p className="mt-3 text-rose-300 text-sm">{monitor.data.health.error}</p>}{error && <p className="mt-3 text-rose-300 text-sm">{error}</p>}</section>
    <div className="mt-4 grid grid-cols-[minmax(0,1fr)_minmax(360px,1.25fr)] gap-4">
      <section className="panel panel-risk p-4"><div className="panel-title">异常候选池</div><p className="muted mb-3">按风险等级与时间排序，仅显示由相对活跃度或 IV 重定价触发的研究预警。</p><div className="space-y-2">{prioritizedAlerts.map(alert => <button className="option-alert w-full text-left" key={alert.id} onClick={() => setSymbol(alert.symbol.replace(/^US\./, ""))}><div className="flex justify-between gap-2"><strong>{alert.symbol}</strong><StatusBadge tone={alert.scheduled_event ? "warning" : "info"}>{alert.scheduled_event ? "事件降权" : alert.relation.kind}</StatusBadge></div><div className="mt-2 flex flex-wrap gap-1">{alert.signals.filter(item => item.kind !== "NORMAL").map((item, index) => <StatusBadge key={`${item.kind}-${index}`} tone={tone(item.severity) as "neutral"}>{item.kind}</StatusBadge>)}</div><p className="muted mt-2 text-xs">{formatTime(alert.created_at)} · {alert.relation.message}</p></button>)}{!monitor.isLoading && !prioritizedAlerts.length && <div className="news-empty-state compact"><strong>暂无异常预警</strong><span>预热完成后，系统只显示具有研究意义的异常。</span></div>}</div></section>
      <section className="panel panel-evidence p-4"><div className="panel-title">{selected?.symbol || `US.${symbol}`} · 期权链深度</div>{insight.isLoading ? <p className="muted">正在读取期权快照…</p> : selected?.latest ? <><div className="grid grid-cols-4 gap-3 text-sm"><div><span>Call / Put</span><b>{number(selected.latest.aggregate.call_volume)} / {number(selected.latest.aggregate.put_volume)}</b></div><div><span>近 ATM IV</span><b>{number(selected.latest.aggregate.atm_iv * 100, 1)}%</b></div><div><span>远月 IV</span><b>{number(selected.latest.aggregate.far_iv * 100, 1)}%</b></div><div><span>最活跃执行价</span><b>{number(selected.latest.aggregate.top_strike, 2)}</b></div></div>{selected.latest.scheduled_event && <div className="news-warning mt-3">SCHEDULED EVENT：未来 7 日存在已知财报，方向性判断已降权。</div>}<div className="mt-4 space-y-2">{selected.latest.signals.map((item, index) => <article className="option-signal" key={`${item.kind}-${index}`}><StatusBadge tone={tone(item.severity) as "neutral"}>{item.kind}</StatusBadge><strong className="ml-2">{item.direction || "研究状态"}</strong><p className="muted mt-1 text-sm">{item.message}</p></article>)}</div><p className="muted mt-3 text-xs">{selected.relation?.kind} · {selected.relation?.message}</p><details className="news-raw-evidence mt-4"><summary>原始合约证据（最多 12 条）</summary><div className="overflow-x-auto"><table><thead><tr><th>合约</th><th>类型</th><th>执行价</th><th>到期/DTE</th><th>成交量/OI</th><th>IV</th></tr></thead><tbody>{(selected.contracts ?? []).map(row => <tr key={row.contract}><td>{row.contract}</td><td>{row.option_type}</td><td>{number(row.strike, 2)}</td><td>{row.expiry} / {row.dte}</td><td>{number(row.volume)} / {number(row.open_interest)}</td><td>{number(row.iv * 100, 1)}%</td></tr>)}</tbody></table></div></details><p className="muted mt-3 text-xs">{selected.limitations?.join(" ")}</p></> : <div className="news-empty-state compact"><strong>{insight.data?.message || "尚未采集期权快照"}</strong><span>扫描该标的后将展示期权链、IV 与异常证据。</span></div>}</section>
    </div>
  </div>;
}
