import { useQuery } from "@tanstack/react-query";
import { RefreshCw } from "lucide-react";
import { useState } from "react";
import { PageHeader, StatusBadge } from "@/components/ui/workspace";

type Candidate = { symbol:string; name:string; industry:string; market_cap_usd:number; data_as_of:string; delta_low_tradable_on:string; gpmapro:{date:string;markers:string[]}; gap_trading_days:number; active_on:string; trend:string; news:{status:string;reason:string;veto:boolean}; invalidates:string };
type Pool = { status:string; snapshot_id?:string; scanned_at?:string; market?:{regime:string}; coverage?:Record<string,number>; health?:{unscanned?:Record<string,number>;source?:{reachable?:boolean}}; buy_candidates?:Candidate[]; market_risk_candidates?:Candidate[]; disclaimer?:string };
type Evaluation = { horizons:Array<{horizon:number;oos_sample_count:number;oos_mean_net_return:number|null}> };
async function request<T>(path:string, init?:RequestInit):Promise<T> { const r=await fetch(path,init); if(!r.ok) throw new Error(await r.text()); return r.json(); }
const tone=(x:string)=>["CONFIRM","NORMAL","BULLISH"].includes(x)?"positive":["VETO","RISK","CRISIS"].includes(x)?"negative":"neutral";
const money=(x:number)=>new Intl.NumberFormat("zh-CN",{notation:"compact",maximumFractionDigits:1,style:"currency",currency:"USD"}).format(x);
function Card({item,risk}:{item:Candidate;risk?:boolean}) { const [open,setOpen]=useState(false); return <article className={`stock-pool-card ${risk?"stock-pool-filtered":"stock-pool-focus"}`}><div className="stock-pool-card-top"><div><b>{item.symbol} · {item.name}</b><span>{item.industry}</span></div><StatusBadge tone={tone(item.news.status) as "positive"}>{item.news.status}</StatusBadge></div><div className="stock-pool-tags"><StatusBadge tone="positive">DELTA LOW {item.delta_low_tradable_on}</StatusBadge><StatusBadge tone="positive">GPMA {item.gpmapro.markers.join("/")}</StatusBadge><StatusBadge tone={tone(item.trend) as "positive"}>{item.trend}</StatusBadge></div><dl className="stock-pool-facts"><div><dt>市值</dt><dd>{money(item.market_cap_usd)}</dd></div><div><dt>GPMA 日期</dt><dd>{item.gpmapro.date}</dd></div><div><dt>间隔</dt><dd>{item.gap_trading_days} 个交易日</dd></div><div><dt>数据截至</dt><dd>{item.data_as_of}</dd></div></dl><p className="stock-pool-summary">新闻：{item.news.reason} · 信号于 {item.active_on} 生效。</p><button className="text-button" type="button" onClick={()=>setOpen(v=>!v)}>{open?"收起详情":"展开详情"}</button>{open&&<div className="stock-pool-details"><p><b>失效条件：</b>{item.invalidates}</p><p><b>新闻状态：</b>{item.news.status}{item.news.veto?"（风险提示不改变技术入选事实）":""}</p></div>}</article> }
function Section({title,description,items,risk}:{title:string;description:string;items:Candidate[];risk?:boolean}) { return <section className="stock-pool-section panel panel-evidence"><div className="stock-pool-column-heading"><div><span>{description}</span><h2>{title}</h2></div><b>{items.length}</b></div>{items.length?<div className="stock-pool-list">{items.map(x=><Card item={x} risk={risk} key={x.symbol}/>)}</div>:<div className="news-empty-state compact"><strong>暂无候选</strong><span>只显示 DELTA LOW 与最终 GPMAPRO 买入标记相隔不超过 3 个交易日的标的。</span></div>}</section> }
export function StockPool() { const pool=useQuery({queryKey:["stock-pool"],queryFn:()=>request<Pool>("/api/stock-pool/latest"),retry:false}); const evaluation=useQuery({queryKey:["stock-pool-evaluation"],queryFn:()=>request<Evaluation>("/api/stock-pool/evaluation"),retry:false}); const [running,setRunning]=useState(false); const [error,setError]=useState<string|null>(null); const scan=async()=>{setRunning(true);setError(null);try{await request<Pool>("/api/stock-pool/scan",{method:"POST"});await Promise.all([pool.refetch(),evaluation.refetch()])}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setRunning(false)}}; const data=pool.data,coverage=data?.coverage,reasons=Object.entries(data?.health?.unscanned??{}); return <div className="terminal-page stock-pool-page"><PageHeader title="股票池" description="全美股大市值买入筛选池：仅 DELTA LOW × 最终 GPMAPRO 买入标记配对；新闻只展示确认或风险提示。" actions={<button className="primary-button inline-flex items-center gap-1" onClick={()=>void scan()} disabled={running}><RefreshCw size={14}/>{running?"扫描中…":"刷新扫描"}</button>}/>{error&&<p className="error-banner mb-3">{error}</p>}<section className="stock-pool-status panel panel-evidence"><div><span>最近扫描</span><strong>{data?.scanned_at?new Date(data.scanned_at).toLocaleString("zh-CN",{hour12:false}):"尚无快照"}</strong><p>{data?.snapshot_id??"等待美东收盘后 16:15 自动运行"}</p></div><div className="stock-pool-status-metrics"><div><span>市场状态</span><b><StatusBadge tone={tone(data?.market?.regime??"UNKNOWN") as "positive"}>{data?.market?.regime??"—"}</StatusBadge></b></div><div><span>上市股票</span><b>{coverage?.listed??"—"}</b></div><div><span>≥ $30B</span><b>{coverage?.cap_eligible??"—"}</b></div><div><span>已同步日线</span><b>{coverage?.synchronized??"—"}</b></div></div></section>{data?.status==="NO_SNAPSHOT"?<div className="news-empty-state panel panel-evidence mt-4"><strong>尚未生成全市场快照</strong><span>刷新会执行相同的只读流程；自动任务只在美东交易日 16:15 后生成每日不可变快照。</span></div>:<><div className="stock-pool-grid mt-4"><Section title="买入筛选池" description="技术条件完整，市场非 RISK/CRISIS" items={data?.buy_candidates??[]}/><Section title="市场风险下候选" description="技术条件完整，但当前不建议新增" items={data?.market_risk_candidates??[]} risk/></div><section className="stock-pool-health panel panel-evidence mt-4"><div><span>未扫描 / 异常</span><h2>{data?.health?.source?.reachable===false?"OpenD 未连接":"数据同步健康度"}</h2><p>数据失败不会作为技术性 FILTERED 卡片展示，也不会进入买入筛选池。</p></div><div>{reasons.length?reasons.map(([x,n])=><span key={x}>{x} · {n}</span>):<span>无待处理异常</span>}</div></section><section className="stock-pool-evaluation panel panel-research mt-4"><div><span>样本外评估</span><h2>次一交易日开盘入场，计入固定往返成本</h2><p>按时间顺序滚动切分，统计 5 / 10 / 20 个交易日净收益。</p></div><div>{(evaluation.data?.horizons??[]).map(x=><span key={x.horizon}>{x.horizon}D · {x.oos_sample_count} OOS · {x.oos_mean_net_return==null?"—":`${(x.oos_mean_net_return*100).toFixed(2)}%`}</span>)}</div></section></>}<p className="panel-footnote mt-3">{data?.disclaimer??"研究候选，非自动交易或投资建议。"}</p></div> }
