import { useMemo, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Download, FlaskConical, ShieldCheck } from "lucide-react";
import { resolveMarketCodes, type Market } from "@/lib/marketCode";

type Metric = { sample_count: number; average_gross_return: number | null; average_net_return: number | null; median_net_return: number | null; positive_rate: number | null; average_mfe: number | null; average_mae: number | null; net_return_ci_95: [number | null, number | null] };
type Trade = { symbol: string; signal_date: string; entry_date: string; exit_date: string; net_return: number; holding_bars: number; exit_reason: string };
type Assessment = { label: "WORTH_CONTINUING" | "NOT_ROBUST" | "INSUFFICIENT_EVIDENCE"; failed_checks: string[]; active_symbols: number; dominant_etf_share: number | null };
type Strategy = { id: string; entry_label: string; exit_label: string; metrics: Metric; random_baseline: Metric; b_only_baseline: Metric; per_symbol?: Record<string, Metric & { net_return_sum: number }>; net_edge_vs_random: number | null; research_assessment?: Assessment; trades: Trade[] };
type Audit = { forecast_count: number; completed_count: number; positive_rate: number | null; average_window_return_10: number | null; records: Array<{ published_at: string; event_type: string; window_start: string; window_end: string; confidence: number; window_return_10: number }> };
type Result = { run_metadata: { fingerprint: string; execution: string; formula: string; cost_bps_per_side: number }; delta_audit: Record<string, Audit>; strategies: Strategy[]; walk_forward: Record<string, { summary: { window_count: number; active_window_count: number; positive_window_rate: number | null; average_test_return: number | null; verdict: string } }>; assumptions: Record<string, string> };
type Snapshot = { snapshot_id: string; code: string; timeframe: string; autype: string; bar_count: number };
type RunStatus = { run_id: string; status: "QUEUED" | "RUNNING" | "COMPLETED" | "FAILED"; error?: string; reused: boolean; progress: { stage: string; progress: number; symbol: string | null; completed_symbols: number; total_symbols: number } };

const pct = (value: number | null | undefined) => value == null ? "—" : `${value >= 0 ? "+" : ""}${(value * 100).toFixed(2)}%`;
const csv = (rows: Array<Array<string | number | null>>) => rows.map(row => row.map(value => `"${String(value ?? "").replaceAll('"', '""')}"`).join(",")).join("\n");

export function StrategyLab() {
  const [symbols, setSymbols] = useState("VXN"); const [market, setMarket] = useState<Market>("US"); const [source, setSource] = useState<"futu" | "local">("futu");
  const [cost, setCost] = useState(10); const [confirmation, setConfirmation] = useState(5); const [maxHold, setMaxHold] = useState(60);
  const [start, setStart] = useState(""); const [end, setEnd] = useState(""); const [selected, setSelected] = useState("DELTA_LOW_THEN_B__FIRST_S");
  const [runId, setRunId] = useState<string | null>(null);
  const parsedSymbols = useMemo(() => resolveMarketCodes(symbols, market), [symbols, market]);
  const symbolList = parsedSymbols.codes;
  const snapshots = useQuery<{ snapshots: Snapshot[] }>({ queryKey: ["futu-snapshots"], queryFn: async () => { const response = await fetch("/api/data/futu/snapshots"); if (!response.ok) throw new Error(await response.text()); return response.json(); }, retry: false });
  const snapshotIds = Object.fromEntries(symbolList.flatMap(symbol => { const snapshot = snapshots.data?.snapshots.find(item => item.code === symbol && item.timeframe === "1d" && item.autype === "QFQ" && item.bar_count > 0); return snapshot ? [[symbol, snapshot.snapshot_id]] : []; }));
  const snapshotId = symbolList.length === 1 ? snapshotIds[symbolList[0]] : undefined;
  const allSnapshotsReady = symbolList.length > 0 && Object.keys(snapshotIds).length === symbolList.length;
  const payload = { symbols: symbolList, timeframe: "1d", cost_bps_per_side: cost, confirmation_bars: confirmation, max_hold_bars: maxHold, ...(start ? { start_date: start } : {}), ...(end ? { end_date: end } : {}), ...(source === "futu" && symbolList.length === 1 && snapshotId ? { snapshot_id: snapshotId } : {}), ...(source === "futu" && symbolList.length > 1 && allSnapshotsReady ? { snapshot_ids: snapshotIds } : {}) };
  const enabled = Boolean(symbolList.length) && (source === "local" || allSnapshotsReady);
  const query = useQuery<Result>({ queryKey: ["strategy-lab", payload], queryFn: async () => { const response = await fetch("/api/backtest/strategy-lab", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); if (!response.ok) throw new Error(await response.text()); return response.json(); }, enabled, retry: false, staleTime: 30_000 });
  const etfSnapshots = useMemo(() => snapshots.data?.snapshots.filter(item => ["US.SPY", "US.QQQ", "US.IWM", "US.XLF", "US.XLE", "US.XLV", "US.XLI", "US.XLU"].includes(item.code) && item.timeframe === "1d" && item.autype === "QFQ") ?? [], [snapshots.data]);
  const fullPayload = useMemo(() => ({ symbols: etfSnapshots.map(item => item.code), timeframe: "1d", start_date: "2012-01-03", end_date: "2026-08-14", cost_bps_per_side: 10, confirmation_bars: 5, max_hold_bars: 60, snapshot_ids: Object.fromEntries(etfSnapshots.map(item => [item.code, item.snapshot_id])) }), [etfSnapshots]);
  const runStatus = useQuery<RunStatus>({ queryKey: ["strategy-lab-run", runId], queryFn: async () => { const response = await fetch(`/api/backtest/strategy-lab/runs/${runId}`); if (!response.ok) throw new Error(await response.text()); return response.json(); }, enabled: Boolean(runId), refetchInterval: data => data.state.data?.status === "COMPLETED" || data.state.data?.status === "FAILED" ? false : 1500 });
  const fullResult = useQuery<Result>({ queryKey: ["strategy-lab-run-result", runId], queryFn: async () => { const response = await fetch(`/api/backtest/strategy-lab/runs/${runId}/result`); if (!response.ok) throw new Error(await response.text()); return response.json(); }, enabled: runStatus.data?.status === "COMPLETED" });
  const launchFullRun = async () => { const response = await fetch("/api/backtest/strategy-lab/runs", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(fullPayload) }); if (!response.ok) throw new Error(await response.text()); const started: RunStatus = await response.json(); setRunId(started.run_id); };
  const result = fullResult.data ?? query.data;
  const chosen = result?.strategies.find(item => item.id === selected) ?? result?.strategies[0];
  const audit = Object.entries(result?.delta_audit ?? {});
  const download = () => { if (runId && runStatus.data?.status === "COMPLETED") { window.open(`/api/backtest/strategy-lab/runs/${runId}/export`, "_blank"); return; } if (!result) return; const rows = [["entry_rule", "exit_rule", "sample_count", "average_net_return", "median_net_return", "positive_rate", "random_average_net_return", "edge_vs_random", "run_fingerprint"], ...result.strategies.map(item => [item.entry_label, item.exit_label, item.metrics.sample_count, item.metrics.average_net_return, item.metrics.median_net_return, item.metrics.positive_rate, item.random_baseline.average_net_return, item.net_edge_vs_random, result.run_metadata.fingerprint])]; const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([csv(rows)], { type: "text/csv" })); link.download = "strategy-lab-matrix.csv"; link.click(); URL.revokeObjectURL(link.href); };
  return <div className="space-y-4">
    <section className="panel p-4"><div className="flex items-start justify-between gap-4"><div><div className="panel-title flex items-center gap-2"><FlaskConical size={16} className="text-cyan-300"/>策略实验配置</div><p className="muted">仅做多；信号在收盘确认、下一交易日开盘成交。DELTA 只使用此前已发布的预测窗口。</p></div><button className="secondary-button inline-flex items-center gap-1" disabled={!result} onClick={download}><Download size={14}/>导出矩阵 CSV</button></div><div className="mt-3 grid grid-cols-6 gap-2"><select className="terminal-input" value={source} onChange={event => setSource(event.target.value as "futu" | "local")}><option value="futu">富途 OpenD 快照</option><option value="local">本地 CSV</option></select><select className="terminal-input" value={market} onChange={event => setMarket(event.target.value as Market)}><option value="A">A 股</option><option value="HK">港股</option><option value="US">美股</option></select><input className="terminal-input" value={symbols} onChange={event => setSymbols(event.target.value.toUpperCase())} placeholder="600519, 000001 / 00700 / AAPL"/><input className="terminal-input" type="number" min="0" value={cost} onChange={event => setCost(Number(event.target.value))} title="单边成本 bps"/><select className="terminal-input" value={confirmation} onChange={event => setConfirmation(Number(event.target.value))}><option value={0}>同日确认</option><option value={3}>3 日确认窗</option><option value={5}>5 日确认窗</option><option value={10}>10 日确认窗</option></select><input className="terminal-input" type="number" min="5" max="120" value={maxHold} onChange={event => setMaxHold(Number(event.target.value))} title="最大持有日"/></div>{parsedSymbols.error ? <p className="error-banner mt-2">{parsedSymbols.error}</p> : <div className="mt-2 flex gap-2"><input className="terminal-input" type="date" value={start} onChange={event => setStart(event.target.value)} aria-label="回测开始日期"/><input className="terminal-input" type="date" value={end} onChange={event => setEnd(event.target.value)} aria-label="回测结束日期"/><span className="terminal-input text-xs text-zinc-400">{source === "futu" ? `${Object.keys(snapshotIds).length} / ${symbolList.length} 已锁定快照` : "本地数据"}</span></div>}<div className="mt-4 border-t border-zinc-800 pt-3"><button className="primary-button" disabled={etfSnapshots.length !== 8 || runStatus.data?.status === "QUEUED" || runStatus.data?.status === "RUNNING"} onClick={() => void launchFullRun()}>运行 8 ETF 全历史验证</button><span className="ml-3 text-xs text-zinc-400">锁定 2012-01-03 至 2026-08-14 的 8 个 ETF 快照</span>{runStatus.data && <p className={runStatus.data.status === "FAILED" ? "error-banner mt-3" : "muted mt-3"}>任务 {runStatus.data.run_id} · {runStatus.data.status} · {runStatus.data.progress.stage} · {Math.round(runStatus.data.progress.progress * 100)}% · {runStatus.data.progress.symbol ?? "准备中"}（{runStatus.data.progress.completed_symbols}/{runStatus.data.progress.total_symbols}）{runStatus.data.error ? `：${runStatus.data.error}` : ""}</p>}</div></section>
    {query.isError && <p className="error-banner">实验运行失败：{String(query.error)}</p>}
    {query.isLoading && <section className="panel p-4 text-sm text-cyan-200">正在逐日回放 DELTA 预测并计算策略矩阵…</section>}
    {result && <><section className="grid grid-cols-4 gap-4"><div className="panel p-4"><span>候选策略</span><b>{result.strategies.length}</b></div><div className="panel p-4"><span>执行假设</span><b className="text-sm">次日开盘</b></div><div className="panel p-4"><span>单边成本</span><b>{result.run_metadata.cost_bps_per_side} bp</b></div><div className="panel p-4"><span>实验指纹</span><b className="font-mono text-xs">{result.run_metadata.fingerprint.slice(0, 12)}</b></div></section>
      <section className="panel p-4"><div className="panel-title flex items-center gap-2"><ShieldCheck size={16} className="text-cyan-300"/>DELTA 预测审计</div><p className="muted">此处衡量的是此前已发布的 DELTA 窗口在窗口结束后的方向性结果，不使用事后标出的历史高低点。</p><div className="mt-3 grid grid-cols-4 gap-3">{audit.map(([symbol, item]) => <div className="border border-zinc-800 p-3" key={symbol}><b>{symbol}</b><span>冻结预测 {item.forecast_count} / 已完成 {item.completed_count}</span><span>10 日方向胜率 {pct(item.positive_rate)}</span><span>平均方向收益 {pct(item.average_window_return_10)}</span></div>)}</div></section>
      <section className="panel overflow-hidden"><div className="flex items-center justify-between px-4 py-3"><div><div className="panel-title mb-0">买入 × 卖出规则矩阵</div><p className="muted">E1: B；E2: DELTA LOW→B；E3: 底部背离→B；E4: DELTA LOW+底部背离+B。</p></div></div><table><thead><tr><th>买入规则</th><th>卖出规则</th><th>样本</th><th>净收益（95% CI）</th><th>胜率</th><th>随机净收益</th><th>净增益</th><th>样本外</th><th>研究结论</th></tr></thead><tbody>{result.strategies.map(item => { const wf = result.walk_forward[item.id]?.summary; const assessment = item.research_assessment; return <tr className={selected === item.id ? "bg-cyan-950/30" : ""} key={item.id} onClick={() => setSelected(item.id)}><td>{item.entry_label}</td><td>{item.exit_label}</td><td>{item.metrics.sample_count}</td><td>{pct(item.metrics.average_net_return)} <small className="text-zinc-500">[{pct(item.metrics.net_return_ci_95[0])}, {pct(item.metrics.net_return_ci_95[1])}]</small></td><td>{pct(item.metrics.positive_rate)}</td><td>{pct(item.random_baseline.average_net_return)}</td><td className={(item.net_edge_vs_random ?? 0) >= 0 ? "text-emerald-300" : "text-rose-300"}>{pct(item.net_edge_vs_random)}</td><td>{wf?.verdict ?? "—"}</td><td className={assessment?.label === "WORTH_CONTINUING" ? "text-emerald-300" : "text-amber-300"}>{assessment?.label ?? "快速实验"}{assessment?.failed_checks.length ? <small className="block text-zinc-500">{assessment.failed_checks.join(", ")}</small> : null}</td></tr>; })}</tbody></table></section>
      {chosen && <section className="panel overflow-hidden"><div className="flex items-center justify-between px-4 py-3"><div><div className="panel-title mb-0">逐笔审计：{chosen.entry_label} → {chosen.exit_label}</div><p className="muted">点击矩阵中的任一规则以查看；所有日期均可追溯。</p></div><span>样本外 {pct(result.walk_forward[chosen.id]?.summary.positive_window_rate)}</span></div>{chosen.per_symbol && <div className="border-y border-zinc-800 px-4 py-3 text-xs"><b>逐 ETF 贡献</b><div className="mt-2 flex flex-wrap gap-2">{Object.entries(chosen.per_symbol).map(([symbol, item]) => <span className="border border-zinc-700 px-2 py-1" key={symbol}>{symbol} · {item.sample_count} 笔 · 合计 {pct(item.net_return_sum)}</span>)}</div></div>}<table><thead><tr><th>标的</th><th>信号日</th><th>入场（次日开盘）</th><th>出场</th><th>持有</th><th>净收益</th><th>退出原因</th></tr></thead><tbody>{chosen.trades.slice(0, 100).map((trade, index) => <tr key={`${trade.symbol}-${trade.entry_date}-${index}`}><td>{trade.symbol}</td><td>{trade.signal_date}</td><td>{trade.entry_date}</td><td>{trade.exit_date}</td><td>{trade.holding_bars} bars</td><td className={trade.net_return >= 0 ? "text-emerald-300" : "text-rose-300"}>{pct(trade.net_return)}</td><td>{trade.exit_reason}</td></tr>)}</tbody></table></section>}
      <p className="px-1 text-xs text-zinc-500">公式：{result.run_metadata.formula}。研究结果不构成实盘收益承诺；当前标的池可能存在幸存者偏差。</p></>}
  </div>;
}
